add gjbasegamelayer, gmanager, gamemanager, appdelegate address
geode-sdk/bindings pull request #149
Opened 2024-01-29 02:03 UTC by qwix456

2024-01-29 02:04 UTC, matcool commented on bindings/2.205/GeometryDash.bro
> -	virtual TodoReturn firstLoad();
why were these virtuals removed

2024-01-29 02:06 UTC, Cvolton commented
why are the addresses added to 2.205, latest gd windows is 2.204

2024-01-29 02:06 UTC, matcool commented on bindings/2.205/GeometryDash.bro
> +	static GameManager* sharedState() = 0x121540;
epic syntax error

2024-01-29 02:07 UTC, matcool commented on bindings/2.205/GeometryDash.bro
> +	cocos2d::ccColor3B colorForIdx(int) = 0x126090;
epic syntax error

2024-01-29 02:07 UTC, matcool commented
> why are the addresses added to 2.205, latest gd windows is 2.204

i just noticed that . lmao

2024-01-29 02:07 UTC, matcool requested changes
these are all 2.204 addresses

2024-01-30 02:03 UTC, matcool commented
still on 2.205..

2024-02-03 13:49 UTC, closed without merging