Add More Variables Names and include more Reverse engineered code snippets
geode-sdk/bindings pull request #192
Opened 2024-02-09 20:12 UTC by CallocGD

I didn't Go super deep with some of these functions since I wanted to make that I was positive that they would closely match the real gd code before I added them in. If you don't want these code snippets be my guest and let me know if I should remove them.

2024-02-09 20:24 UTC, CallocGD commented
Seems there is a problem with CMake again so I don't know what triggered it to go off this time...

2024-02-10 15:53 UTC, altalk23 requested changes

2024-02-10 15:53 UTC, altalk23 commented on bindings/2.204/GeometryDash.bro
> +	void inline banUser(int);
we don't use inline like this, this should be removed

2024-02-10 15:53 UTC, altalk23 commented on bindings/2.204/GeometryDash.bro
> +	void ProcessHttpRequest((gd::string endpoint, gd::string params, gd::string tag, GJHttpType httpType) = win 0xf3bf0;
i have 0 idea how the extra ( here doesnt cause a syntax error

2024-02-10 16:03 UTC, merged