fmod stuff
geode-sdk/bindings pull request #286
Opened 2024-03-16 01:34 UTC by TheSillyDoggo

2024-03-16 04:04 UTC, SpaghettDev commented on bindings/2.204/GeometryDash.bro
> +		*(reinterpret_cast<bool*>(reinterpret_cast<uintptr_t>(this) + 0x188)) = false;
MBO jumpscare

2024-03-16 04:04 UTC, SpaghettDev commented
use the members i sent you xd

2024-03-16 13:10 UTC, TheSillyDoggo commented
> use the members i sent you xd

They didn't work xd

2024-03-17 00:29 UTC, matcool requested changes
dont use hardcoded offsets for members, follow our style guides (we put braces on the correct line)

2024-04-01 02:13 UTC, closed without merging