1 Random Windows Address and a member test
geode-sdk/bindings pull request #615
Opened 2024-07-06 06:05 UTC by TheSillyDoggo

2024-07-09 14:17 UTC, Cvolton commented on bindings/2.206/GeometryDash.bro
> +	PAD = android32 0x4, win 0x4, android64 0x48;
scary

2024-07-09 14:21 UTC, matcool commented on bindings/2.206/GeometryDash.bro
> +	PAD = android32 0x4, win 0x4, android64 0x48;
this is certified scary

2024-07-18 12:22 UTC, altalk23 requested changes

2024-07-18 12:22 UTC, altalk23 commented on bindings/2.206/GeometryDash.bro
> +	PAD = android32 0x4, win 0x4, android64 0x48;
yeah no this sounds like a hack

2024-07-31 11:59 UTC, qimiko commented
besides a single windows binding, it does seem like this pull request has become obsolete (proper enhancedgameobject members and tests have been added) so i think it should be closed soon. unless you want to reduce it down to that single windows binding lol

2024-08-08 11:17 UTC, closed without merging